apiVersion: v1
kind: Namespace
metadata:
  name: adhoc-admin
  annotations:
    openshift.io/description: |
      Let automation do something for you -
      Even if it's only halfway
    openshift.io/display-name: Adhoc Automation
