apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - group-admin.yaml
  - limit-range.yaml
  - namespace.yaml
  - quota-compute.yaml
  - quota-storage.yaml
  - rolebinding-admin.yaml
