- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-amq-streams
        path: components/operators/amq-streams/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-aap
        path: components/operators/ansible-automation-platform-operator/operator/overlays/stable-2.4
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-cert-manager
        path: components/operators/openshift-cert-manager-operator/operator/overlays/stable-v1
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-crunchy-postgres
        path: components/operators/crunchy-postgres/operator/overlays/v5
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-elasticsearch
        path: components/operators/elasticsearch/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-local-storage
        path: components/operators/local-storage/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-kubevirt
        path: components/operators/kubevirt-hyperconverged/aggregate/default
#     - cluster: local
#       url: https://kubernetes.default.svc
#       values:
#         name: operator-opendatahub
#         path: components/operators/opendatahub/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-odf
        path: components/operators/openshift-data-foundation/operator/overlays/stable-4.12
    # - cluster: local
    #   url: https://kubernetes.default.svc
    #   values:
    #     name: operator-gitops
    #     path: components/operators/openshift-gitops-operator/aggregate/overlays/hou-edge/
    # - cluster: local
    #   url: https://kubernetes.default.svc
    #   values:
    #     name: operator-keda
    #     path: components/operators/openshift-keda/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-logging
        path: components/operators/openshift-logging/aggregate/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-tekton
        path: components/operators/openshift-pipelines-operator/overlays/latest
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: openshift-serverless-operator
        path: components/operators/openshift-serverless/aggregate/knative-kafka
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-rhods
        path: components/operators/rhods-operator/aggregate/overlays/edge-lab
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-web-terminal
        path: components/operators/web-terminal-operator/operator/overlays/fast
